"""One-command bootstrap for the Fleet Control Plane.

Non-interactive by design so an AI agent or a human can run it unattended:

    python setup_fleet.py --init                          # single machine
    python setup_fleet.py --init --nodes local,node-b     # add peers
    python setup_fleet.py --init --telegram-token XXX --telegram-chat-id 123

Writes $FLEET_HOME/.env (0600), generates the Ed25519 receipt keypair, and
initialises the task database. Existing values are preserved unless --force.
"""
from __future__ import annotations

import argparse
import os
import secrets
import sys

from config import Config
from init_db import init_db
from keys import ensure_keys


def parse_env(path):
    entries, order = {}, []
    if path.is_file():
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.rstrip("\n")
            if line.strip() and not line.strip().startswith("#") and "=" in line:
                key = line.split("=", 1)[0].strip()
                entries[key] = line
                order.append(key)
            elif line.strip():
                order.append(None)
    return entries, order


def write_env(path, entries, order):
    lines = ["# Fleet Control Plane configuration",
             "# Generated by setup_fleet.py - contains secrets. Keep at 0600.",
             ""]
    for key in order:
        if key is None:
            continue
        lines.append(entries[key])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def upsert(entries, order, key, value):
    if key not in entries:
        order.append(key)
    entries[key] = f"{key}={value}"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Bootstrap the Fleet Control Plane")
    ap.add_argument("--init", action="store_true", help="run the bootstrap")
    ap.add_argument("--node-id", default=None, help="this machine's node name")
    ap.add_argument("--nodes", default=None, help="comma-separated node roster")
    ap.add_argument("--host", default=None, help="bind address (default 127.0.0.1)")
    ap.add_argument("--port", default=None, help="bind port (default 8088)")
    ap.add_argument("--telegram-token", default=None)
    ap.add_argument("--telegram-chat-id", default=None)
    ap.add_argument("--key-id", default=None, help="receipt key id")
    ap.add_argument("--force", action="store_true", help="regenerate secrets")
    args = ap.parse_args(argv)

    if not args.init:
        ap.print_help()
        return 2

    cfg = Config()
    hostname = os.uname().nodename.lower() if hasattr(os, "uname") else os.environ.get("COMPUTERNAME", "local").lower()
    node_id = (args.node_id or args.nodes.split(",")[0].strip()
               if args.nodes else args.node_id) or hostname[:24] or "local"

    print("[1/5] Preparing FLEET_HOME...")
    print(f"      {cfg.home}")
    entries, order = parse_env(cfg.env_file)

    print("[2/5] Configuring identity and node roster...")
    upsert(entries, order, "FLEET_NODE_ID", node_id)
    upsert(entries, order, "FLEET_NODES", args.nodes or cfg.get("FLEET_NODES") or node_id)
    upsert(entries, order, "FLEET_HOST", args.host or cfg.get("FLEET_HOST") or "127.0.0.1")
    upsert(entries, order, "FLEET_PORT", args.port or cfg.get("FLEET_PORT") or "8088")
    if args.key_id:
        upsert(entries, order, "FLEET_KEY_ID", args.key_id)

    # A local bearer token so single-machine setups work immediately.
    key_name = f"FLEET_KEY_{node_id.upper().replace('-', '_')}"
    if args.force or key_name not in entries:
        token = "flk_" + secrets.token_urlsafe(32)
        upsert(entries, order, key_name, token)
        print(f"      generated {key_name}")
    else:
        print(f"      kept existing {key_name}")

    # Give every additional node its own token.
    roster = [n.strip() for n in (args.nodes or cfg.get("FLEET_NODES") or node_id).split(",") if n.strip()]
    for peer in roster:
        name = f"FLEET_KEY_{peer.upper().replace('-', '_')}"
        if name not in entries or args.force:
            upsert(entries, order, name, "flk_" + secrets.token_urlsafe(32))
            print(f"      generated {name}")

    if args.telegram_token:
        upsert(entries, order, "TELEGRAM_BOT_TOKEN", args.telegram_token)
    if args.telegram_chat_id:
        upsert(entries, order, "TELEGRAM_CHAT_ID", args.telegram_chat_id)

    write_env(cfg.env_file, entries, order)
    print(f"      wrote {cfg.env_file}")

    # Reload so the rest of the run sees the freshly written values.
    cfg = Config()
    cfg.file_env = parse_env(cfg.env_file)[0]
    cfg.file_env = {k: v.split("=", 1)[1] for k, v in cfg.file_env.items()}

    print("[3/5] Generating Ed25519 receipt keypair...")
    _, public, generated = ensure_keys(cfg, force=False)
    print(f"      {'generated' if generated else 'reused'} {cfg.key_path}")
    print(f"      published {cfg.jwks_path}")

    print("[4/5] Initialising task database...")
    db = init_db(verbose=False)
    print(f"      {db} (WAL)")

    print("[5/5] Verifying...")
    ok = cfg.key_path.exists() and cfg.jwks_path.exists() and cfg.db_path.exists() and cfg.node_keys
    print(f"      node_id   : {cfg.node_id}")
    print(f"      nodes     : {', '.join(cfg.nodes)}")
    print(f"      node keys : {len(cfg.node_keys)}")
    print(f"      telegram  : {'enabled' if cfg.telegram_enabled else 'disabled (optional)'}")
    print(f"      result    : {'OK' if ok else 'INCOMPLETE'}")

    if not ok:
        return 1

    print("\nNext:\n  python app.py      # start the API\n  python worker.py   # start the worker")
    return 0


if __name__ == "__main__":
    sys.exit(main())
